### ISSUE TITLE
Error trying to change profile picture.

### ISSUE THREAD

**Issue by namelessperson0** [deso-protocol/identity#116] opened 2022-01-25 18:29 UTC
Getting this error` 414 Request-URI Too Large` when changing profile picture and signing the transaction.
Error occurs when image is more than 150 kb.

Issue similar to https://github.com/deso-protocol/identity/issues/85

**Comment by maebeam** [comment] 2022-01-25 20:01
Duplicate of #85 ◡̈

**Closed by maebeam** 2022-01-25 20:01 UTC
